version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    parallel: 2
    working_directory: /go/src/github.com/palantir/tfjson
    steps:
      - checkout
      - run: go version
      - run: go test
      - run: go build .
