version: 2.1

orbs:
  go: palantir/go@0.0.11

jobs:
  verify:
    parameters:
      executor:
        description: |
          The executor used for this job.
        type: executor
    executor: << parameters.executor >>
    steps:
      - go/setup:
          restore-mod-cache: false
      - run: go version
      - run: go build .

workflows:
  version: 2
  verify:
    jobs:
      - verify:
          name: verify-go-1.12
          executor:
            name: go/golang
            owner-repo: palantir/tfjson
            version: 1.12.2
            module: false
      - verify:
          name: verify-go-1.11
          executor:
            name: go/golang
            owner-repo: palantir/tfjson
            version: 1.11.8
            module: false
      - verify:
          name: verify-go-1.10
          executor:
            name: go/golang
            owner-repo: palantir/tfjson
            version: 1.10.8
            module: false
