version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    parallel: 2

    working_directory: /go/src/github.com/palantir/tfjson
    steps:
      - checkout
      - run:
          name: "Verify Go version"
          command: go version
      - run:
          name: "Install terraform"
          command: go install /go/src/github.com/hashicorp/terraform
      - run:
          name: "Run Go Tests"
          command: go test
          environment:
            GO111MODULE: 'on'
      - run:
          name: "Verify that package builds"
          command: go build .
