version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    parallel: 2

    working_directory: /go/src/github.com/palantir/tfjson
    steps:
      - checkout
      - run:
          name: "Verify Go version"
          command: go version; echo $PATH
      - run:
          name: "Run Go Tests"
          command: go test
          environment:
            GO111MODULE: 'on'
            PATH: '\$PATH:\$GOPATH/bin'
      - run:
          name: "Verify that package builds"
          command: go build .
