version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/palantir/tfjson
    environment:
      GO111MODULE: 'on'
    steps:
      - checkout
      - run:
          name: "Verify Go version"
          command: go version
      - run:
          name: "Get dependencies"
          command: go get
      - run:
          name: "Install terraform"
          command: go install /go/pkg/mod/github.com/hashicorp/terraform@v0.11.13
      - run:
          name: "Run Go Tests"
          command: go test
      - run:
          name: "Verify that package builds"
          command: go build .
